name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          npm install -g gh-pages
          npm run build
          gh-pages -d build
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: List all PHP files
        run: |
          Get-ChildItem -Path web\src -Recurse -Filter *.php | ForEach-Object { $_.FullName }
        shell: pwsh

      - name: Run all PHP files
        run: |
          $files = Get-ChildItem -Path web\src -Recurse -Filter *.php
          foreach ($file in $files) {
              Write-Host "Running $($file.FullName)"
              php $file.FullName
          }
        shell: pwsh
